### ISSUE TITLE
Support wiremock extensions

### ISSUE THREAD

**Issue by ayevee** [holomekc/wiremock#28]
Please add support for wiremock extensions (e.g. webhooks).

This requires adding extension jar to classpath and passing extension class to wiremock `--extensions` parameter.

Seems that two changes are required in the image:
1. Add a directory for extension jars, e.g. `/home/extensions`
2. Change cmd from
```sh
java -XX:+PrintFlagsFinal $JAVA_OPTIONS -jar /home/wiremock/wiremock.jar
```
to
```sh
java -XX:+PrintFlagsFinal $JAVA_OPTIONS -cp /home/wiremock/wiremock.jar:/home/extensions/* com.github.tomakehurst.wiremock.standalone.WireMockServerRunner
```
3. `--extensions` parameter can be added to `WIREMOCK_OPTIONS` environment variable, e.g.
```
WIREMOCK_OPTIONS: "--port=8088,--https-port=8443,--extensions=org.wiremock.webhooks.Webhooks"
```

**Comment by wavesrcomn** [comment]
I'm having the same issue. 
I'm trying to run wiremock UI with Webhooks extension too and it doesn't work.
Using this command for windows cmd:
`java -cp wiremock-jre8-standalone-2.33.2.1.jar;wiremock-webhooks-extension-2.33.2.1.jar com.github.tomakehurst.wiremock.standalone.WireMockServerRunner --extensions org.wiremock.webhooks.Webhooks `

Error:
```
Exception in thread "main" java.lang.ClassNotFoundException: org.wiremock.webhooks.Webhooks
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at com.github.tomakehurst.wiremock.extension.ExtensionLoader$3.apply(ExtensionLoader.java:71)
        at com.github.tomakehurst.wiremock.extension.ExtensionLoader$3.apply(ExtensionLoader.java:67)
        at wiremock.com.google.common.collect.Iterators$6.transform(Iterators.java:829)
        at wiremock.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
        at wiremock.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:52)
        at wiremock.com.google.common.collect.Maps.uniqueIndex(Maps.java:1391)
        at wiremock.com.google.common.collect.Maps.uniqueIndex(Maps.java:1353)
        at com.github.tomakehurst.wiremock.extension.ExtensionLoader.asMap(ExtensionLoader.java:40)
        at com.github.tomakehurst.wiremock.extension.ExtensionLoader.loadExtension(ExtensionLoader.java:32)
        at com.github.tomakehurst.wiremock.extension.ExtensionLoader.load(ExtensionLoader.java:36)
        at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.buildExtensions(CommandLineOptions.java:363)
        at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.<init>(CommandLineOptions.java:354)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:56)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:140)
```

A jar without UI works fine.
Can you please fix this? or may be you have any workarounds?

**Comment by ayevee** [comment]
@wavesrcomn, I'm using the following Dockerfile at the moment:
```Dockerfile
FROM holomekc/wiremock-gui:latest

COPY --chown=wiremock:users wiremock-webhooks-extension-2.33.2.jar /home/wiremock
CMD java -XX:+PrintFlagsFinal $JAVA_OPTIONS \
    -cp /home/wiremock/wiremock.jar:/home/wiremock/wiremock-webhooks-extension-2.33.2.jar \
    com.github.tomakehurst.wiremock.standalone.WireMockServerRunner
```
And `--extensions=org.wiremock.webhooks.Webhooks` parameter in WIREMOCK_OPTIONS environment variable.

**Comment by holomekc** [comment]
Hi,
Sorry for my inactivity. I will check this next weekend. Thanks for providing so much info.
Br,
Christopher

**Comment by holomekc** [comment]
Hi. I hope I adjusted it properly. You should be able to mount the extensions in the /home/wiremock/extensions directory now. [2.34.0.0](https://hub.docker.com/layers/holomekc/wiremock-gui/2.34.0.0/images/sha256-ae8b713053689d44e1d9b1a7eed5c66e5b7726e04672d86ec85eec07435b75bb?context=explore)
