### ISSUE TITLE
Missing wiremock-gui property causes exception.

### ISSUE THREAD

**Issue by fdutton** [holomekc/wiremock#41]
This occurs if the mapping contains metadata but does not have wiremock-gui. Line 147 of JsonFileMappingsSource attempts to check for a missing wirelock-gui but Metadata throws an exception if the key is not in the map.

`2023-09-23 14:06:33.053 Unrecoverable error handling admin request
java.lang.IllegalArgumentException: wiremock-gui' not present
at wiremock.com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
at com.github.tomakehurst.wiremock.common.Metadata.checkKeyPresent(Metadata.java:101)
at com.github.tomakehurst.wiremock.common.Metadata.checkPresenceValidityAndCast(Metadata.java:84)
at com.github.tomakehurst.wiremock.common.Metadata.getMap(Metadata.java:63)
at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.hasFolderDefinition(JsonFileMappingsSource.java:147)
`

**Comment by holomekc** [comment]
Hi thx for the feedback. I will fix it soon-ish.

**Comment by holomekc** [comment]
Fixed in https://github.com/holomekc/wiremock/releases/tag/3.1.0.0-ui
